"""Generated from QShell abi/qshell-abi.json; do not edit."""

VERSION = 2
BEAT_BYTES = 64
HEADER_BYTES = 48
MAGIC = 0x32485351

RECORD_CLASS_SYNDROME = 0x1
RECORD_CLASS_CORRECTION = 0x2
RECORD_CLASS_CONTROL = 0x3
RECORD_CLASS_ERROR = 0x4

FLAG_END_OF_ROUND = 0x1
FLAG_CONTROL_RESPONSE = 0x2

SCHEMA_OPAQUE_LOOPBACK = 0x1
SCHEMA_HELIOS_PHENOM_SYNDROME = 0x10001
SCHEMA_HELIOS_SPARSE_CORRECTION = 0x10002
SCHEMA_MICROBLOSSOM_COMMAND = 0x20001
SCHEMA_MICROBLOSSOM_RESPONSE = 0x20002
SCHEMA_MICROBLOSSOM_DECODE_REQUEST = 0x20003
SCHEMA_MICROBLOSSOM_DECODE_RESULT = 0x20004
SCHEMA_PAULI_FRAME_XOR = 0x30001
SCHEMA_QUEKUF_D3_SYNDROME = 0x50001
SCHEMA_QUEKUF_D3_CORRECTION = 0x50002
SCHEMA_CONTROL = 0xffff0001
SCHEMA_ERROR = 0xffff0002

ERROR_SCOPE_DROP_RECORD = 0x1
ERROR_SCOPE_ABORT_ROUND = 0x2
ERROR_SCOPE_DISABLE_ROUTE = 0x3
ERROR_SCOPE_QUARANTINE_SERVICE = 0x4

ERROR_MALFORMED_RECORD = 0x1
ERROR_UNSUPPORTED_ABI = 0x2
ERROR_UNKNOWN_RECORD_CLASS = 0x3
ERROR_INVALID_FLAGS = 0x4
ERROR_INVALID_LENGTH = 0x5
ERROR_INVALID_KEEP = 0x6
ERROR_UNEXPECTED_LAST = 0x7
ERROR_UNKNOWN_CAPABILITY = 0x10
ERROR_SOURCE_MISMATCH = 0x11
ERROR_CONTEXT_MISMATCH = 0x12
ERROR_SCHEMA_MISMATCH = 0x13
ERROR_ROUND_REPLAY = 0x14
ERROR_SEQUENCE_MISMATCH = 0x15
ERROR_INGRESS_ROUTE_VERSION_NONZERO = 0x16
ERROR_QUEUE_OVERFLOW = 0x17
ERROR_ROUTE_DISABLED = 0x18
ERROR_STALE_CORRECTION = 0x20
ERROR_CORRECTION_PRODUCER_MISMATCH = 0x21
ERROR_CORRECTION_DESTINATION_MISMATCH = 0x22
ERROR_CORRECTION_VERSION_MISMATCH = 0x23
ERROR_CORRECTION_SCHEMA_MISMATCH = 0x24
ERROR_CORRECTION_DUPLICATE = 0x25
ERROR_CONTROL_MALFORMED = 0x30
ERROR_UNSUPPORTED_CONTROL = 0x31
ERROR_INVALID_TRANSITION = 0x32
ERROR_VERSION_EXHAUSTED = 0x33
ERROR_SERVICE_UNAVAILABLE = 0x40
ERROR_SERVICE_QUARANTINED = 0x41

OFFSET_MAGIC = 0
OFFSET_ABI_VERSION = 4
OFFSET_RECORD_CLASS = 5
OFFSET_FLAGS = 6
OFFSET_HEADER_BYTES = 8
OFFSET_RESERVED = 10
OFFSET_PAYLOAD_BYTES = 12
OFFSET_CONTEXT_ID = 16
OFFSET_ROUND_ID = 20
OFFSET_SCHEMA_ID = 24
OFFSET_SOURCE_ENDPOINT_ID = 28
OFFSET_DESTINATION_ENDPOINT_ID = 32
OFFSET_ROUTE_CAPABILITY_ID = 36
OFFSET_ROUTE_VERSION = 40
OFFSET_RECORD_SEQUENCE = 44
